In [ ]:
lista = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]

soma = sum(lista)
media = soma / len(lista)

print(media)

3144.222

In [ ]:
lista_numeros = []

for i in range(5):
    numero = int(input("Digite um número: "))
    lista_numeros.append(numero)

lista_numeros.sort(reverse=True)
print(lista_numeros)

Digite um número: 1
Digite um número: 2
Digite um número: 3
Digite um número: 4
Digite um número: 5
[5, 4, 3, 2, 1]

In [ ]:
n = int(input("Digite um numero: "))

for i in range(2, n+1):
  if n % i == 0:
    print(i)

Digite um numero: 15
3
5
15

Para um estudo envolvendo o nível de multiplicação de bactérias em uma colônia, foi coletado o número de bactérias por dia (em milhares) e pode ser observado a seguir: [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]. Tendo esses valores, faça um código que gere uma lista contendo o percentual de crescimento de bactérias por dia, comparando o número de bactérias em cada dia com o número de bactérias do dia anterior. Dica: para calcular o percentual de crescimento usamos a seguinte equação: 100 * (amostra_atual - amostra_passada) / (amostra_passada).

In [ ]:
colonia_bacterias = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
colonia_percentual = []

for i in range(1, len(colonia_bacterias)):
  amostra_atual = colonia_bacterias[i]
  amostra_passada = colonia_bacterias[i-1]

  percentual = 100 * (amostra_atual - amostra_passada) / (amostra_passada)
  colonia_percentual.append(percentual)

print(colonia_percentual)

[75.00000000000001, 57.142857142857125, 51.51515151515153, 56.0, 44.87179487179489, 46.90265486725664, 51.20481927710843, 50.59760956175297, 50.52910052910054]

Para uma seleção de produtos alimentícios, precisamos separar o conjunto de IDs dados por números inteiros sabendo que os produtos com ID par são doces e os com ID ímpar são amargos. Monte um código que colete 10 IDs. Depois, calcule e mostre a quantidade de produtos doces e amargos.

In [ ]:
doce = 0
amargo = 0

for i in range(10):
  id = int(input("Digite um ID: "))
  if id % 2 == 0:
    doce += 1
  else:
    amargo += 1

print("Doce: ", doce)
print("Amargo: ", amargo)

Digite um ID: 1
Digite um ID: 2
Digite um ID: 5
Digite um ID: 6
Digite um ID: 7
Digite um ID: 8
Digite um ID: 4
Digite um ID: 23
Digite um ID: 66
Digite um ID: 544
Doce:  6
Amargo:  4

Desenvolva um programa que informa a nota de um(a) aluno(a) de acordo com suas respostas. Ele deve pedir a resposta desse(a) aluno(a) para cada questão e é preciso verificar se a resposta foi igual ao gabarito. Cada questão vale um ponto e existem as alternativas A, B, C ou D.



Gabarito da prova:
01 - D
02 - A
03 - C
04 - B
05 - A
06 - D
07 - C
08 - C
09 - A
10 - B

In [ ]:
acertos = 0
gabarito = ["D", "A", "C", "B", "A", "D", "C", "C", "A", "B"]

for i in range(1, 11):
  resposta = input(f"Digite a resposta da pergunta {i} (A, B, C, ou D): ").upper()

  if resposta !=

  if resposta == gabarito[i-1]:
    acertos += 1

print(f'Você acertou {acertos} perguntas')

Digite a resposta da pergunta 1 (A, B, C, ou D): d
Digite a resposta da pergunta 2 (A, B, C, ou D): a
Digite a resposta da pergunta 3 (A, B, C, ou D): c
Digite a resposta da pergunta 4 (A, B, C, ou D): b
Digite a resposta da pergunta 5 (A, B, C, ou D): a
Digite a resposta da pergunta 6 (A, B, C, ou D): d
Digite a resposta da pergunta 7 (A, B, C, ou D): c
Digite a resposta da pergunta 8 (A, B, C, ou D): d
Digite a resposta da pergunta 9 (A, B, C, ou D): d
Digite a resposta da pergunta 10 (A, B, C, ou D): d
Você acertou 7 perguntas

Um instituto de meteorologia deseja fazer um estudo de temperatura média de cada mês do ano. Para isso, você precisa fazer um código que colete e armazene essas temperaturas médias em uma lista. Depois, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual e em que mês elas ocorreram, mostrando os meses por extenso (Janeiro, Fevereiro, etc.).

In [2]:
temperaturas = []

meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]


for i in range(1, 13):
  temp = int(input("Digite a temperatura do mês: "))
  temperaturas.append(temp)


media = sum(temperaturas) / len(temperaturas)

print(f'A média anual é {media}')

print(f'As temperaturas acima da média anual foram: ')
for i in range(len(temperaturas)):
  if temperaturas[i] > media:
    print(f'{temperaturas[i]}°C em {meses[i]}')

Digite a temperatura do mês: 3
Digite a temperatura do mês: 4
Digite a temperatura do mês: 5
Digite a temperatura do mês: 6
Digite a temperatura do mês: 9
Digite a temperatura do mês: 15
Digite a temperatura do mês: 37
Digite a temperatura do mês: 3
Digite a temperatura do mês: 6
Digite a temperatura do mês: 2
Digite a temperatura do mês: 7
Digite a temperatura do mês: 11
A média anual é 9.0
As temperaturas acima da média anual foram:
15°C em Junho
37°C em Julho
11°C em Dezembro

Uma empresa de e-commerce está interessada em analisar as vendas dos seus produtos. Os dados das vendas foram armazenados em um dicionário:

{'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}

Escreva um código que calcule o total de vendas e o produto mais vendido.

In [4]:
produtos = {'Produto A': 300, 'Produto B': 80, 'Produto C': 60, 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}

total_vendas = sum(produtos.values())

produto_mais_vendido = max(produtos, key=produtos.get)

print(f'O total de vendas foi de {total_vendas}')
print(f'O produto mais vendido foi {produto_mais_vendido}')

O total de vendas foi de 920
O produto mais vendido foi Produto A

Uma pesquisa de mercado foi feita para decidir qual design de marca infantil mais agrada as crianças. A pesquisa foi feita e o votos computados podem ser observados abaixo:

'''
Tabela de votos da marca
Design 1 - 1334 votos
Design 2 - 982 votos
Design 3 - 1751 votos
Design 4 - 210 votos
Design 5 - 1811 votos
'''

Adapte os dados fornecidos para uma estrutura de dicionário. A partir dele, informe o design vencedor e a porcentagem de votos recebidos.

In [5]:
designs = {'Design 1': 1334, 'Design 2': 982, 'Design 3': 1751, 'Design 4': 210, 'Design 5': 1811}

total_votos = sum(designs.values())

print(f'O design vencedor foi o {max(designs, key=designs.get)} com {max(designs.values())} votos')

O design vencedor foi o Design 5 com 1811 votos

As pessoas colaboradoras de um setor da empresa que você trabalha vão receber um abono correspondente a 10% do salário devido ao ótimo desempenho do time. O setor financeiro solicitou sua ajuda para a verificação das consequências financeiras que esse abono irá gerar nos recursos. Assim, foi encaminhada para você uma lista com os salários que receberão o abono: [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]. O abono de cada colaborador(a) não pode ser inferior a 200. Em código, transforme cada um dos salários em chaves de um dicionário e o abono de cada salário no elemento. Depois, informe o total de gastos com o abono, quantos(as) colaboradores(as) receberam o abono mínimo e qual o maior valor de abono fornecido.

In [6]:
salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]

abonos = {}
total_gastos = 0
colaboradores_abono_minimo = 0
maior_abono = 0

for salario in salarios:
  abono = salario * 0.1
  if abono < 200:
    abono = 200
    colaboradores_abono_minimo += 1
  abonos[salario] = abono
  total_gastos += abono
  if abono > maior_abono:
    maior_abono = abono


print("Total de gastos com o abono:", total_gastos)
print("Número de colaboradores que receberam o abono mínimo:", colaboradores_abono_minimo)
print("Maior valor de abono fornecido:", maior_abono)

Total de gastos com o abono: 6087.8
Número de colaboradores que receberam o abono mínimo: 2
Maior valor de abono fornecido: 790.3000000000001

Uma equipe de cientistas de dados está estudando a diversidade biológica em uma floresta. A equipe fez a coleta de informações sobre o número de espécies de plantas e animais em cada área dessa floresta e armazenou essas informações em um dicionário. Nele, a chave descreve a área dos dados e os valores nas listas correspondem às espécies de plantas e animais nas áreas, respectivamente.

{'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}

Escreva um código para calcular a média de espécies por área e identificar a área com a maior diversidade biológica. Dica: use as funções built-in sum() e len().

In [8]:
area = {'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}

total_especies = []
for chave, valor in area.items():
  total_especies.append(sum(valor))

media_especies = sum(total_especies) / len(total_especies)

print(f'A média de espécies por área é {media_especies}')


maior_diversidade = 0
area_maior_diversidade = ''

for chave, valor in area.items():
  diversidade = sum(valor)
  if diversidade > maior_diversidade:
    maior_diversidade = diversidade
    area_maior_diversidade = chave


print(f'A área com maior diversidade biológica é a {area_maior_diversidade} com {maior_diversidade} espécies.')

A média de espécies por área é 33258.4
A área com maior diversidade biológica é a Área Centro com 67706 espécies.

O setor de RH da sua empresa te pediu uma ajuda para analisar as idades de colaboradores(as) de 4 setores da empresa. Para isso, foram fornecidos os seguintes dados:

{'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}

Sabendo que cada setor tem 10 colaboradores(as), construa um código que calcule a média de idade de cada setor, a idade média geral entre todos os setores e quantas pessoas estão acima da idade média geral.

In [9]:
setores = {
    'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
    'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
    'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
    'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]
}

media_setores = {}
for setor, idades in setores.items():
  media_setores[setor] = sum(idades) / len(idades)
  print(f"A média de idade do {setor} é: {media_setores[setor]:.2f}")

idades_totais = []
for idades in setores.values():
  idades_totais.extend(idades)

media_geral = sum(idades_totais) / len(idades_totais)
print(f"\nA média de idade geral é: {media_geral:.2f}")

pessoas_acima_media = 0
for idade in idades_totais:
  if idade > media_geral:
    pessoas_acima_media += 1

print(f"\nNúmero de pessoas acima da idade média geral: {pessoas_acima_media}")

A média de idade do Setor A é: 39.90
A média de idade do Setor B é: 42.30
A média de idade do Setor C é: 35.80
A média de idade do Setor D é: 36.50

A média de idade geral é: 38.62

Número de pessoas acima da idade média geral: 18